# Generated by Django 5.0.6 on 2024-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_user_is_organsior_alter_lead_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organsior',
            field=models.BooleanField(default=True),
        ),
    ]
