# Generated by Django 5.0.6 on 2024-07-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_user_is_agent_remove_user_is_organsior'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organsior',
            field=models.BooleanField(default=True),
        ),
    ]
