# Generated by Django 5.0.6 on 2024-07-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_user_is_agent_user_is_organsior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organsior',
            new_name='is_organizer',
        ),
    ]
